=== RSJosePacheco/ejemplo/bibliografia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="bibliografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="libro" minOccurs="1" maxOccurs="4">
					<xs:complexType>
						<xs:sequence>
							<!-- NODO AUTOR -->
							<xs:element name="autor" minOccurs="1" maxOccurs="3">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<!-- <xs:attribute name="url" type="xs:string"/> -->
											<xs:attribute name="url" type="xs:string" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<!-- NODO TITULO -->
							<xs:element name="titulo" type="xs:string"/>
							<!-- NODO EDITORIAL -->
							<xs:element name="editorial" type="xs:string"/>
							<!-- NODO AÃ‘O -->
							<xs:element name="anio" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== RSJosePacheco/ejemplo/bibliografia.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliografia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bibliografia.xsd" >
	<libro>
		<autor url="http://integracion.com" >Carlos T.</autor>
		<autor url="http://editorialX.com" >Raymundo S.</autor>
		<titulo>XML Schemas y DTDs</titulo>
		<editorial>Addison-Wesley</editorial>
		<anio>2002</anio>
	</libro>
	<libro>
		<autor url="http://rodolfo.mx" >Rodolfo G.</autor>
		<autor url="http://gonzalo.mx" >Gonzalo Y.</autor>
		<titulo>Aplicaciones Web con JSP y MySQL</titulo>
		<editorial>Adisson-Wesley</editorial>
		<anio>2002</anio>
	</libro>
	<libro>
		<autor url="http://rodolfo.mx" >Rodolfo G.</autor>
		<autor url="http://gonzalo.mx" >Gonzalo Y.</autor>
		<titulo>Aplicaciones Web con JSP y MySQL</titulo>
		<editorial>Adisson-Wesley</editorial>
		<anio>2002</anio>
	</libro>
</bibliografia>
