=== RSJosePacheco/ejemplo/presentacion2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<<<<<<< HEAD

<xs:element name="presentacion">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="titulo" type="xs:string" />
			<xs:complexType name="diapositiva" >
				
			</xs:complexType>
		</xs:sequence>
	</xs:complexType>
</xs:element>
=======
<xs:element name="presentacion" type="TPresentacion" />
<xs:complexType name="TPresentacion" >
	<xs:sequence>
		<xs:element name="titulo" type="xs:string" />
		<xs:element name="diapositiva" type="Diapositiva" minOccurs="1" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="Diapositiva" >
	<xs:sequence>
		<xs:element name="titulo" type="xs:string"/>
		<xs:element name="contenido" type="xs:string" minOccurs="2" maxOccurs="8" />	
	</xs:sequence>
		<xs:attribute name="nivel" type="xs:string" use="optional" />
</xs:complexType>
</xs:schema>
>>>>>>> auxiliar

=== RSJosePacheco/ejemplo/presentacion2.xml
<?xml version="1.0" encoding="UTF-8"?>
<presentacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="presentacion2.xsd" >
	<titulo>
		Clase de XML
	</titulo>
	<diapositiva nivel="basico" >
		<titulo>Breve historia del XML</titulo>
		<contenido>Basado en SGML</contenido>
		<contenido>Lenguaje de marcado extensible</contenido>
		<contenido>Permite crear vocabularios</contenido>
	</diapositiva>
	<titulo>
		Clase de XML
	</titulo>
	<diapositiva nivel="intermedio" >
		<titulo>Transformaciones XSLT</titulo>
		<contenido>Lenguaje de estilos</contenido>
		<contenido>Genera documentos HTML</contenido>
		<contenido>Puede mezclase con CSS</contenido>

	</diapositiva>
</presentacion>
